// CLIENT
export const SAVE_CLIENT_SUCCESS = "SAVE_CLIENT_SUCCESS";
export const DELETE_CLIENT_SUCCESS = "DELETE_CLIENT_SUCCESS";
export const SEARCH_CLIENT_SUCCESS = "SEARCH_CLIENT_SUCCESS";
export const GET_CLIENT_SUCCESS = "GET_CLIENT_SUCCESS";
export const SET_CLIENT_FILTER_COMPLETED = "SET_CLIENT_FILTER_COMPLETED";

// ACCOUNT
export const SAVE_ACCOUNT_SUCCESS = "SAVE_ACCOUNT_SUCCESS";
export const DELETE_ACCOUNT_SUCCESS = "DELETE_ACCOUNT_SUCCESS";
export const SEARCH_ACCOUNT_SUCCESS = "SEARCH_ACCOUNT_SUCCESS";
export const GET_ACCOUNT_SUCCESS = "GET_ACCOUNT_SUCCESS";
export const SET_ACCOUNT_FILTER_COMPLETED = "SET_ACCOUNT_FILTER_COMPLETED";
export const APPROVE_ACCOUNT_SUCCESS = "APPROVE_ACCOUNT_SUCCESS";
export const DECLINE_ACCOUNT_SUCCESS = "DECLINE_ACCOUNT_SUCCESS";
export const CANCEL_ACCOUNT_SUCCESS = "CANCEL_ACCOUNT_SUCCESS";
export const SAVE_ACCOUNT_COMMENT_SUCCESS = "SAVE_ACCOUNT_COMMENT_SUCCESS";

// API
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

//Lookup Set
export const GET_TRANSACTION_TYPE_SUCCESS = "GET_TRANSACTION_TYPE_SUCCESS";
export const GET_DURATION_TYPE_SUCCESS = "GET_DURATION_TYPE_SUCCESS";
export const GET_REPAYMENT_SCHEDULE_SUCCESS = "GET_REPAYMENT_SCHEDULE_SUCCESS";
export const GET_RECORD_STATUS_SUCCESS = "GET_RECORD_STATUS_SUCCESS";
export const GET_SEED_CONSTANT_TYPE_SUCCESS = "GET_SEED_CONSTANT_TYPE_SUCCESS";
export const GET_CHANGE_OPERATIONS_SUCCESS = "GET_CHANGE_OPERATIONS_SUCCESS";
export const GET_ACCOUNT_STATUS_SUCCESS = "GET_ACCOUNT_STATUS_SUCCESS";
