// CLIENT
export const SAVE_CLIENT_SUCCESS = "SAVE_CLIENT_SUCCESS";
export const DELETE_CLIENT_SUCCESS = "DELETE_CLIENT_SUCCESS";
export const SEARCH_CLIENT_SUCCESS = "SEARCH_CLIENT_SUCCESS";
export const GET_CLIENT_SUCCESS = "GET_CLIENT_SUCCESS";
export const SET_CLIENT_FILTER_BY_COMPLETED = "SET_CLIENT_FILTER_BY_COMPLETED";
// ACCOUNT

export const SAVE_ACCOUNT_SUCCESS = "SAVE_ACCOUNT_SUCCESS";
export const DELETE_ACCOUNT_SUCCESS = "DELETE_ACCOUNT_SUCCESS";
export const SEARCH_ACCOUNT_SUCCESS = "SEARCH_ACCOUNT_SUCCESS";
export const GET_ACCOUNT_SUCCESS = "GET_ACCOUNT_SUCCESS";
export const SET_ACCOUNT_FILTER_BY_COMPLETED =
  "SET_ACCOUNT_FILTER_BY_COMPLETED";

// API
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
